apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "agentic-protection.fullname" . }}-enforce-gateway-only
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ include "agentic-protection.fullname" . }}-sse-safe
          - {{ include "agentic-protection.fullname" . }}-sse-malicious
          - {{ include "agentic-protection.fullname" . }}-grpc-inspection
          - {{ include "agentic-protection.fullname" . }}-h2c
          - {{ include "agentic-protection.fullname" . }}-frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: envoy-gateway-system
      podSelector:
        matchLabels:
          gateway.envoyproxy.io/owning-gateway-name: {{ include "agentic-protection.fullname" . }}-gateway
          gateway.envoyproxy.io/owning-gateway-namespace: {{ .Release.Namespace }}
