apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentic-protection.fullname" . }}-h2cll-safe
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.h2cll.safe.replicas }}
  selector:
    matchLabels:
      app: {{ include "agentic-protection.fullname" . }}-h2cll-safe
  template:
    metadata:
      labels:
        app: {{ include "agentic-protection.fullname" . }}-h2cll-safe
    spec:
      containers:
      - name: h2cll-app
        image: {{ .Values.images.h2cll }}
        args:
          - "--port=8080"
          - "--interval={{ .Values.h2cll.safe.interval }}"
        ports:
        - containerPort: 8080
          name: h2c

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentic-protection.fullname" . }}-h2cll-safe-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "agentic-protection.fullname" . }}-h2cll-safe
  ports:
  - name: h2c-port
    port: 8080
    targetPort: 8080
    appProtocol: h2c
