apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentic-protection.fullname" . }}-grpc-inspection
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "agentic-protection.fullname" . }}-grpc-inspection
spec:
  selector:
    matchLabels:
      app: {{ include "agentic-protection.fullname" . }}-grpc-inspection
  template:
    metadata:
      labels:
        app: {{ include "agentic-protection.fullname" . }}-grpc-inspection
    spec:
      containers:
      - name: grpc-inspection-container
        image: {{ .Values.images.grpcInspection }}
        args:
          {{- if .Values.grpcInspection.debug }}
          - "--debug"
          {{- end }}
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
            name: grpc
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
        resources:
          {{- toYaml .Values.grpcInspection.resources | nindent 10 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentic-protection.fullname" . }}-grpc-inspection-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "agentic-protection.fullname" . }}-grpc-inspection
spec:
  type: ClusterIP
  selector:
    app: {{ include "agentic-protection.fullname" . }}-grpc-inspection
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      appProtocol: h2c
